import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merchant = localFont({
  src: "/fonts/Merchant-Medium.woff2",
  variable: "--font-merchant",
});

const neueMontrealFont = localFont({
  src: "fonts/NeueMontreal-Medium.otf",
  variable: "--font-neue-montreal",
});

const everettFont = localFont({
  src: "fonts/Everett-Regular.ttf",
  variable: "--font-everett",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merchant.variable} ${neueMontrealFont.variable} ${everettFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
